/**
 * What the service worker does with each file in `public/`.
 *
 * Vite copies that folder verbatim and tells no plugin what is in it, so unlike
 * the scripts and stylesheets, which the build knows about, this has to be
 * written out by hand. `precache.test.ts` reads the real folder and fails if it
 * holds a file named in none of these lists. That is the point of splitting it
 * three ways rather than keeping one list of what to cache: adding an image
 * forces a decision instead of quietly leaving it unavailable offline.
 */

/**
 * Downloaded during install, before the app has ever been offline.
 *
 * Kept to the shell and the small icons, about 90 KB in total. Everything here
 * is either needed for the app to render at all or is small enough that its
 * cost is lost against the scripts.
 */
export const PRECACHED_PUBLIC = [
  '/site.webmanifest',
  '/favicon.ico',
  '/favicon-16x16.png',
  '/favicon-32x32.png',
  '/favicon-48x48.png',
  '/apple-touch-icon.png',
  // Rendered as the settings drawer heading, and by both static pages below.
  '/icon-192.png',
  // Real documents with real addresses, linked from inside the app and from
  // Ko-fi. They cost 35 KB together and reading the terms offline is fair.
  '/privacy.html',
  '/terms.html',
];

/**
 * Cached the first time somebody looks at them, and not before.
 *
 * These are the panel illustrations, which come to about 320 KB. Most people
 * never open Donate, so precaching them would spend a phone's data at a court
 * on pictures it will not show.
 */
export const RUNTIME_CACHED_PUBLIC = [
  '/account-top.png',
  '/donate-cup.png',
  '/donate-separator.png',
  '/donate-top.png',
  // The two halves of the banner, 62 KB together. Unlike the rest of this list
  // they are on screen from the first paint of every visit — but the first of
  // those visits necessarily has a network, so they land in this cache long
  // before anybody is offline, and precaching them would only make the install
  // more expensive for no gain.
  '/header-left.png',
  '/header-right.jpg',
  '/share-top.png',
  '/share.png',
  // The halftone in the corner of the Setup panel, 20 KB. On screen every
  // session like the banner, and in the same way: it is decoration, so a first
  // visit that has not fetched it yet loses nothing.
  '/corner-dots.png',
  // Named in the manifest and fetched by the operating system when the app is
  // added to a home screen, which only happens online. 252 KB, and the app
  // itself never renders it.
  '/icon-512.png',
  // The same icon inset into Android's 80% safe zone, so its mask crops white
  // rather than cropping the ring. Fetched at install time like the one above,
  // and likewise never rendered by the app.
  '/icon-maskable-512.png',
  // The robin with its alpha, unlike the home screen icons above, which are
  // painted onto opaque white. Worn by the install banner and panel, printed at
  // the head of a paper schedule, and shown full size on the first-run splash.
  // 43 KB, and on screen the moment a new install opens — but that first open
  // necessarily has a network, so it lands here long before anybody is offline.
  '/logo.png',
  // The robin in twelve costumes, about 112 KB across the set, at the head of
  // the settings drawer once in a while. Runtime rather than precached for the
  // same reason as the Donate art: it is a joke, and no install should pay for
  // one up front. A phone that goes offline before its sixth visit to the
  // drawer gets the plain icon it was going to get anyway.
  '/robins/bedtime.webp',
  '/robins/chef.webp',
  '/robins/cowboy.webp',
  '/robins/detective.webp',
  '/robins/hippie.webp',
  '/robins/paddle.webp',
  '/robins/rockstar.webp',
  '/robins/shower.webp',
  '/robins/snorkel.webp',
  '/robins/spa.webp',
  '/robins/toilet.webp',
  '/robins/workout.webp',
  // The manual's screenshots, about 500 KB across twelve files, regenerated by
  // scripts/instructions-shots.mjs. Cached the first time a chapter is read,
  // like the Donate art above: most sessions never open the manual, and the
  // install must not pay for the ones that do.
  '/instructions/account-signin.webp',
  '/instructions/actions.webp',
  '/instructions/keypad.webp',
  '/instructions/partners.webp',
  '/instructions/player-edit.webp',
  '/instructions/players.webp',
  '/instructions/quick-schedule.webp',
  '/instructions/round-card.webp',
  '/instructions/setup.webp',
  '/instructions/share-qr.webp',
  '/instructions/special-types.webp',
  '/instructions/standings.webp',
];

/**
 * Never stored, at any point. The share banner, which exists for scrapers
 * rather than for people, and the two manifest screenshots, which exist for
 * Chrome's install dialog. Both are things another program reads once from a
 * server, so a copy on the phone would never be the copy anybody used.
 *
 * Written out again here rather than imported from `sw.ts`, which owns the copy
 * the worker actually enforces. That file has to stay free of imports, because
 * the build transpiles it on its own without bundling, and this file is read by
 * `vite.config.ts` under a tsconfig with no DOM library. Importing either way
 * round drags one into the wrong project. `precache.test.ts` asserts the two
 * lists agree, which is the part that matters.
 */
export const NEVER_CACHED_PUBLIC = [
  '/og-banner.png',
  '/screenshot-roster.png',
  '/screenshot-schedule.png',
];
