/**
 * Every picture the Instructions chapters use, with its real size, so a page
 * never shifts while one loads. The files live in public/instructions/ and are
 * regenerated by scripts/instructions-shots.mjs; InstructionsPanel.test.ts
 * walks this list against the folder in both directions, so a picture named
 * here without a file, or a file no chapter uses, is a failing test.
 *
 * A .ts of its own rather than an export from the panel, for the same reason
 * accountStyles.ts is: a .tsx exporting both components and data trips
 * react-refresh/only-export-components.
 */
export const SHOTS: Record<string, { width: number; height: number }> = {
  'quick-schedule': { width: 780, height: 1520 },
  players: { width: 780, height: 1400 },
  'player-edit': { width: 780, height: 1688 },
  setup: { width: 780, height: 1520 },
  'special-types': { width: 780, height: 1688 },
  partners: { width: 780, height: 1688 },
  'round-card': { width: 780, height: 1042 },
  keypad: { width: 780, height: 1688 },
  standings: { width: 780, height: 898 },
  actions: { width: 780, height: 1688 },
  'share-qr': { width: 780, height: 1688 },
  'account-signin': { width: 780, height: 1688 },
};
